---
name: pre-commit

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Run pre-commit
        uses: "voxel51/aloha-github-workflows/.github/actions/pre-commit@main"
